name: test user input workflow

on:
  workflow_dispatch:

    inputs:
      number1:
        description: 'First Number'
        default: '0'
        required: true 
      number2:
        description: 'Second Number'
        default: '0'
        required: true 

jobs:
  add_numbers:
    runs-on: ubuntu-latest

    steps:
      - name: add numbers
        id: sum
        run: echo "::set-output name=sum::$((${{ inputs.number1}} + ${{inputs.number2}}))"

      - name: Display sum
        run: echo "the sum of ${{ inputs.number1}} and ${{ inputs.number2}} is ${{ steps.sum.outputs.sum}}"
        
        
